mqtt:
  local:
    clientId: pi-MQTT
    hostname: localhost
    port: 1883
  tb:
    clientId: tb-MQTT
    hostname: demo.thingsboard.io
    port: 1883
    auth-token: 98GVhJAyD5DorEV4c7pd
hr-ms:
  url: http://192.168.1.11:8080/registration/device/
