mqtt:
  local:
    clientId: pi-MQTT
    hostname: 192.168.1.14
    port: 1883
  tb:
    clientId: tb-MQTT
    hostname: demo.thingsboard.io
    port: 1883
    auth-token: 98GVhJAyD5DorEV4c7pd
hr-ms:
  url: https://iot-hr-ms.herokuapp.com/registration/device/
